.code
  PUSH 80			contract Ownable {\n
     addr...
  PUSH 40			contract Ownable {\n
     addr...
  MSTORE 			contract Ownable {\n
     addr...
  CALLVALUE 			constructor() public {\n      ...
  DUP1 			olidity 0
  ISZERO 			a 
  PUSH [tag] 1			a 
  JUMPI 			a 
  PUSH 0			r
  DUP1 			o
  REVERT 			23;\n
 contra
tag 1			a 
  JUMPDEST 			a 
  POP 			constructor() public {\n      ...
  CALLER 			msg.sender
  PUSH 0			owner
  DUP1 			owner
  PUSH 100			owner = msg.sender
  EXP 			owner = msg.sender
  DUP2 			owner = msg.sender
  SLOAD 			owner = msg.sender
  DUP2 			owner = msg.sender
  PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = msg.sender
  MUL 			owner = msg.sender
  NOT 			owner = msg.sender
  AND 			owner = msg.sender
  SWAP1 			owner = msg.sender
  DUP4 			owner = msg.sender
  PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = msg.sender
  AND 			owner = msg.sender
  MUL 			owner = msg.sender
  OR 			owner = msg.sender
  SWAP1 			owner = msg.sender
  SSTORE 			owner = msg.sender
  POP 			owner = msg.sender
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Ownable {\n
     addr...
  DUP1 			contract Ownable {\n
     addr...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Ownable {\n
     addr...
  PUSH 0			contract Ownable {\n
     addr...
  CODECOPY 			contract Ownable {\n
     addr...
  PUSH 0			contract Ownable {\n
     addr...
  RETURN 			contract Ownable {\n
     addr...
.data
  0:
    .code
      PUSH 80			contract Ownable {\n
     addr...
      PUSH 40			contract Ownable {\n
     addr...
      MSTORE 			contract Ownable {\n
     addr...
      PUSH 4			contract Ownable {\n
     addr...
      CALLDATASIZE 			contract Ownable {\n
     addr...
      LT 			contract Ownable {\n
     addr...
      PUSH [tag] 1			contract Ownable {\n
     addr...
      JUMPI 			contract Ownable {\n
     addr...
      PUSH 0			contract Ownable {\n
     addr...
      CALLDATALOAD 			contract Ownable {\n
     addr...
      PUSH 100000000000000000000000000000000000000000000000000000000			contract Ownable {\n
     addr...
      SWAP1 			contract Ownable {\n
     addr...
      DIV 			contract Ownable {\n
     addr...
      PUSH FFFFFFFF			contract Ownable {\n
     addr...
      AND 			contract Ownable {\n
     addr...
      DUP1 			contract Ownable {\n
     addr...
      PUSH 8DA5CB5B			contract Ownable {\n
     addr...
      EQ 			contract Ownable {\n
     addr...
      PUSH [tag] 2			contract Ownable {\n
     addr...
      JUMPI 			contract Ownable {\n
     addr...
      DUP1 			contract Ownable {\n
     addr...
      PUSH F2FDE38B			contract Ownable {\n
     addr...
      EQ 			contract Ownable {\n
     addr...
      PUSH [tag] 3			contract Ownable {\n
     addr...
      JUMPI 			contract Ownable {\n
     addr...
    tag 1			contract Ownable {\n
     addr...
      JUMPDEST 			contract Ownable {\n
     addr...
      PUSH 0			contract Ownable {\n
     addr...
      DUP1 			contract Ownable {\n
     addr...
      REVERT 			contract Ownable {\n
     addr...
    tag 2			address public owner
      JUMPDEST 			address public owner
      CALLVALUE 			address public owner
      DUP1 			olidity 0
      ISZERO 			a 
      PUSH [tag] 4			a 
      JUMPI 			a 
      PUSH 0			r
      DUP1 			o
      REVERT 			23;\n
 contra
    tag 4			a 
      JUMPDEST 			a 
      POP 			address public owner
      PUSH [tag] 5			address public owner
      PUSH [tag] 6			address public owner
      JUMP 			address public owner
    tag 5			address public owner
      JUMPDEST 			address public owner
      PUSH 40			address public owner
      MLOAD 			address public owner
      DUP1 			address public owner
      DUP3 			address public owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			address public owner
      AND 			address public owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			address public owner
      AND 			address public owner
      DUP2 			address public owner
      MSTORE 			address public owner
      PUSH 20			address public owner
      ADD 			address public owner
      SWAP2 			address public owner
      POP 			address public owner
      POP 			address public owner
      PUSH 40			address public owner
      MLOAD 			address public owner
      DUP1 			address public owner
      SWAP2 			address public owner
      SUB 			address public owner
      SWAP1 			address public owner
      RETURN 			address public owner
    tag 3			function transferOwnership(add...
      JUMPDEST 			function transferOwnership(add...
      CALLVALUE 			function transferOwnership(add...
      DUP1 			olidity 0
      ISZERO 			a 
      PUSH [tag] 7			a 
      JUMPI 			a 
      PUSH 0			r
      DUP1 			o
      REVERT 			23;\n
 contra
    tag 7			a 
      JUMPDEST 			a 
      POP 			function transferOwnership(add...
      PUSH [tag] 8			function transferOwnership(add...
      PUSH 4			function transferOwnership(add...
      DUP1 			function transferOwnership(add...
      CALLDATASIZE 			function transferOwnership(add...
      SUB 			function transferOwnership(add...
      DUP2 			function transferOwnership(add...
      ADD 			function transferOwnership(add...
      SWAP1 			function transferOwnership(add...
      DUP1 			function transferOwnership(add...
      DUP1 			function transferOwnership(add...
      CALLDATALOAD 			function transferOwnership(add...
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			function transferOwnership(add...
      AND 			function transferOwnership(add...
      SWAP1 			function transferOwnership(add...
      PUSH 20			function transferOwnership(add...
      ADD 			function transferOwnership(add...
      SWAP1 			function transferOwnership(add...
      SWAP3 			function transferOwnership(add...
      SWAP2 			function transferOwnership(add...
      SWAP1 			function transferOwnership(add...
      POP 			function transferOwnership(add...
      POP 			function transferOwnership(add...
      POP 			function transferOwnership(add...
      PUSH [tag] 9			function transferOwnership(add...
      JUMP 			function transferOwnership(add...
    tag 8			function transferOwnership(add...
      JUMPDEST 			function transferOwnership(add...
      STOP 			function transferOwnership(add...
    tag 6			address public owner
      JUMPDEST 			address public owner
      PUSH 0			address public owner
      DUP1 			address public owner
      SWAP1 			address public owner
      SLOAD 			address public owner
      SWAP1 			address public owner
      PUSH 100			address public owner
      EXP 			address public owner
      SWAP1 			address public owner
      DIV 			address public owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			address public owner
      AND 			address public owner
      DUP2 			address public owner
      JUMP [out]			address public owner
    tag 9			function transferOwnership(add...
      JUMPDEST 			function transferOwnership(add...
      PUSH 0			owner
      DUP1 			owner
      SWAP1 			owner
      SLOAD 			owner
      SWAP1 			owner
      PUSH 100			owner
      EXP 			owner
      SWAP1 			owner
      DIV 			owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner
      AND 			owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			newOwner != owner
      AND 			newOwner != owner
      DUP2 			newOwner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			newOwner != owner
      AND 			newOwner != owner
      EQ 			newOwner != owner
      ISZERO 			newOwner != owner
      ISZERO 			require(\n             newOwne...
      ISZERO 			require(\n             newOwne...
      PUSH [tag] 11			require(\n             newOwne...
      JUMPI 			require(\n             newOwne...
      PUSH 40			require(\n             newOwne...
      MLOAD 			require(\n             newOwne...
      PUSH 8C379A000000000000000000000000000000000000000000000000000000000			require(\n             newOwne...
      DUP2 			require(\n             newOwne...
      MSTORE 			require(\n             newOwne...
      PUSH 4			require(\n             newOwne...
      ADD 			require(\n             newOwne...
      DUP1 			require(\n             newOwne...
      DUP1 			require(\n             newOwne...
      PUSH 20			require(\n             newOwne...
      ADD 			require(\n             newOwne...
      DUP3 			require(\n             newOwne...
      DUP2 			require(\n             newOwne...
      SUB 			require(\n             newOwne...
      DUP3 			require(\n             newOwne...
      MSTORE 			require(\n             newOwne...
      PUSH D			require(\n             newOwne...
      DUP2 			require(\n             newOwne...
      MSTORE 			require(\n             newOwne...
      PUSH 20			require(\n             newOwne...
      ADD 			require(\n             newOwne...
      DUP1 			require(\n             newOwne...
      PUSH 77726F6E67206164647265737300000000000000000000000000000000000000			require(\n             newOwne...
      DUP2 			require(\n             newOwne...
      MSTORE 			require(\n             newOwne...
      POP 			require(\n             newOwne...
      PUSH 20			require(\n             newOwne...
      ADD 			require(\n             newOwne...
      SWAP2 			require(\n             newOwne...
      POP 			require(\n             newOwne...
      POP 			require(\n             newOwne...
      PUSH 40			require(\n             newOwne...
      MLOAD 			require(\n             newOwne...
      DUP1 			require(\n             newOwne...
      SWAP2 			require(\n             newOwne...
      SUB 			require(\n             newOwne...
      SWAP1 			require(\n             newOwne...
      REVERT 			require(\n             newOwne...
    tag 11			require(\n             newOwne...
      JUMPDEST 			require(\n             newOwne...
      DUP1 			newOwner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			OwnershipTransferred(owner, ne...
      AND 			OwnershipTransferred(owner, ne...
      PUSH 0			owner
      DUP1 			owner
      SWAP1 			owner
      SLOAD 			owner
      SWAP1 			owner
      PUSH 100			owner
      EXP 			owner
      SWAP1 			owner
      DIV 			owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner
      AND 			owner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			OwnershipTransferred(owner, ne...
      AND 			OwnershipTransferred(owner, ne...
      PUSH 8BE0079C531659141344CD1FD0A4F28419497F9722A3DAAFE3B4186F6B6457E0			OwnershipTransferred(owner, ne...
      PUSH 40			OwnershipTransferred(owner, ne...
      MLOAD 			OwnershipTransferred(owner, ne...
      PUSH 40			OwnershipTransferred(owner, ne...
      MLOAD 			OwnershipTransferred(owner, ne...
      DUP1 			OwnershipTransferred(owner, ne...
      SWAP2 			OwnershipTransferred(owner, ne...
      SUB 			OwnershipTransferred(owner, ne...
      SWAP1 			OwnershipTransferred(owner, ne...
      LOG3 			OwnershipTransferred(owner, ne...
      DUP1 			newOwner
      PUSH 0			owner
      DUP1 			owner
      PUSH 100			owner = newOwner
      EXP 			owner = newOwner
      DUP2 			owner = newOwner
      SLOAD 			owner = newOwner
      DUP2 			owner = newOwner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = newOwner
      MUL 			owner = newOwner
      NOT 			owner = newOwner
      AND 			owner = newOwner
      SWAP1 			owner = newOwner
      DUP4 			owner = newOwner
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			owner = newOwner
      AND 			owner = newOwner
      MUL 			owner = newOwner
      OR 			owner = newOwner
      SWAP1 			owner = newOwner
      SSTORE 			owner = newOwner
      POP 			owner = newOwner
      POP 			function transferOwnership(add...
      JUMP [out]			function transferOwnership(add...
    .data
