.code
  PUSH 80			contract Bank{\n
     mapping(...
  PUSH 40			contract Bank{\n
     mapping(...
  MSTORE 			contract Bank{\n
     mapping(...
  CALLVALUE 			contract Bank{\n
     mapping(...
  DUP1 			olidity 0
  ISZERO 			a 
  PUSH [tag] 1			a 
  JUMPI 			a 
  PUSH 0			r
  DUP1 			o
  REVERT 			23;\n
 contra
tag 1			a 
  JUMPDEST 			a 
  POP 			contract Bank{\n
     mapping(...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Bank{\n
     mapping(...
  DUP1 			contract Bank{\n
     mapping(...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Bank{\n
     mapping(...
  PUSH 0			contract Bank{\n
     mapping(...
  CODECOPY 			contract Bank{\n
     mapping(...
  PUSH 0			contract Bank{\n
     mapping(...
  RETURN 			contract Bank{\n
     mapping(...
.data
  0:
    .code
      PUSH 80			contract Bank{\n
     mapping(...
      PUSH 40			contract Bank{\n
     mapping(...
      MSTORE 			contract Bank{\n
     mapping(...
      PUSH 4			contract Bank{\n
     mapping(...
      CALLDATASIZE 			contract Bank{\n
     mapping(...
      LT 			contract Bank{\n
     mapping(...
      PUSH [tag] 1			contract Bank{\n
     mapping(...
      JUMPI 			contract Bank{\n
     mapping(...
      PUSH 0			contract Bank{\n
     mapping(...
      CALLDATALOAD 			contract Bank{\n
     mapping(...
      PUSH 100000000000000000000000000000000000000000000000000000000			contract Bank{\n
     mapping(...
      SWAP1 			contract Bank{\n
     mapping(...
      DIV 			contract Bank{\n
     mapping(...
      PUSH FFFFFFFF			contract Bank{\n
     mapping(...
      AND 			contract Bank{\n
     mapping(...
      DUP1 			contract Bank{\n
     mapping(...
      PUSH 3506F54D			contract Bank{\n
     mapping(...
      EQ 			contract Bank{\n
     mapping(...
      PUSH [tag] 2			contract Bank{\n
     mapping(...
      JUMPI 			contract Bank{\n
     mapping(...
      DUP1 			contract Bank{\n
     mapping(...
      PUSH 47734892			contract Bank{\n
     mapping(...
      EQ 			contract Bank{\n
     mapping(...
      PUSH [tag] 3			contract Bank{\n
     mapping(...
      JUMPI 			contract Bank{\n
     mapping(...
      DUP1 			contract Bank{\n
     mapping(...
      PUSH 5FD8C710			contract Bank{\n
     mapping(...
      EQ 			contract Bank{\n
     mapping(...
      PUSH [tag] 4			contract Bank{\n
     mapping(...
      JUMPI 			contract Bank{\n
     mapping(...
      DUP1 			contract Bank{\n
     mapping(...
      PUSH C0E317FB			contract Bank{\n
     mapping(...
      EQ 			contract Bank{\n
     mapping(...
      PUSH [tag] 5			contract Bank{\n
     mapping(...
      JUMPI 			contract Bank{\n
     mapping(...
    tag 1			contract Bank{\n
     mapping(...
      JUMPDEST 			contract Bank{\n
     mapping(...
      PUSH 0			contract Bank{\n
     mapping(...
      DUP1 			contract Bank{\n
     mapping(...
      REVERT 			contract Bank{\n
     mapping(...
    tag 2			function contractHoldEth() pub...
      JUMPDEST 			function contractHoldEth() pub...
      CALLVALUE 			function contractHoldEth() pub...
      DUP1 			olidity 0
      ISZERO 			a 
      PUSH [tag] 6			a 
      JUMPI 			a 
      PUSH 0			r
      DUP1 			o
      REVERT 			23;\n
 contra
    tag 6			a 
      JUMPDEST 			a 
      POP 			function contractHoldEth() pub...
      PUSH [tag] 7			function contractHoldEth() pub...
      PUSH [tag] 8			function contractHoldEth() pub...
      JUMP 			function contractHoldEth() pub...
    tag 7			function contractHoldEth() pub...
      JUMPDEST 			function contractHoldEth() pub...
      PUSH 40			function contractHoldEth() pub...
      MLOAD 			function contractHoldEth() pub...
      DUP1 			function contractHoldEth() pub...
      DUP3 			function contractHoldEth() pub...
      DUP2 			function contractHoldEth() pub...
      MSTORE 			function contractHoldEth() pub...
      PUSH 20			function contractHoldEth() pub...
      ADD 			function contractHoldEth() pub...
      SWAP2 			function contractHoldEth() pub...
      POP 			function contractHoldEth() pub...
      POP 			function contractHoldEth() pub...
      PUSH 40			function contractHoldEth() pub...
      MLOAD 			function contractHoldEth() pub...
      DUP1 			function contractHoldEth() pub...
      SWAP2 			function contractHoldEth() pub...
      SUB 			function contractHoldEth() pub...
      SWAP1 			function contractHoldEth() pub...
      RETURN 			function contractHoldEth() pub...
    tag 3			function getUserBalance(addres...
      JUMPDEST 			function getUserBalance(addres...
      CALLVALUE 			function getUserBalance(addres...
      DUP1 			olidity 0
      ISZERO 			a 
      PUSH [tag] 9			a 
      JUMPI 			a 
      PUSH 0			r
      DUP1 			o
      REVERT 			23;\n
 contra
    tag 9			a 
      JUMPDEST 			a 
      POP 			function getUserBalance(addres...
      PUSH [tag] 10			function getUserBalance(addres...
      PUSH 4			function getUserBalance(addres...
      DUP1 			function getUserBalance(addres...
      CALLDATASIZE 			function getUserBalance(addres...
      SUB 			function getUserBalance(addres...
      DUP2 			function getUserBalance(addres...
      ADD 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      DUP1 			function getUserBalance(addres...
      DUP1 			function getUserBalance(addres...
      CALLDATALOAD 			function getUserBalance(addres...
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			function getUserBalance(addres...
      AND 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      PUSH 20			function getUserBalance(addres...
      ADD 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      SWAP3 			function getUserBalance(addres...
      SWAP2 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      PUSH [tag] 11			function getUserBalance(addres...
      JUMP 			function getUserBalance(addres...
    tag 10			function getUserBalance(addres...
      JUMPDEST 			function getUserBalance(addres...
      PUSH 40			function getUserBalance(addres...
      MLOAD 			function getUserBalance(addres...
      DUP1 			function getUserBalance(addres...
      DUP3 			function getUserBalance(addres...
      DUP2 			function getUserBalance(addres...
      MSTORE 			function getUserBalance(addres...
      PUSH 20			function getUserBalance(addres...
      ADD 			function getUserBalance(addres...
      SWAP2 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      PUSH 40			function getUserBalance(addres...
      MLOAD 			function getUserBalance(addres...
      DUP1 			function getUserBalance(addres...
      SWAP2 			function getUserBalance(addres...
      SUB 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      RETURN 			function getUserBalance(addres...
    tag 4			function withdrawBalance() pub...
      JUMPDEST 			function withdrawBalance() pub...
      CALLVALUE 			function withdrawBalance() pub...
      DUP1 			olidity 0
      ISZERO 			a 
      PUSH [tag] 12			a 
      JUMPI 			a 
      PUSH 0			r
      DUP1 			o
      REVERT 			23;\n
 contra
    tag 12			a 
      JUMPDEST 			a 
      POP 			function withdrawBalance() pub...
      PUSH [tag] 13			function withdrawBalance() pub...
      PUSH [tag] 14			function withdrawBalance() pub...
      JUMP 			function withdrawBalance() pub...
    tag 13			function withdrawBalance() pub...
      JUMPDEST 			function withdrawBalance() pub...
      STOP 			function withdrawBalance() pub...
    tag 5			function addToBalance() public...
      JUMPDEST 			function addToBalance() public...
      PUSH [tag] 15			function addToBalance() public...
      PUSH [tag] 16			function addToBalance() public...
      JUMP 			function addToBalance() public...
    tag 15			function addToBalance() public...
      JUMPDEST 			function addToBalance() public...
      STOP 			function addToBalance() public...
    tag 8			function contractHoldEth() pub...
      JUMPDEST 			function contractHoldEth() pub...
      PUSH 0			uint256
      ADDRESS 			this
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			address(this).balance
      AND 			address(this).balance
      BALANCE 			address(this).balance
      SWAP1 			return address(this).balance
      POP 			return address(this).balance
      SWAP1 			function contractHoldEth() pub...
      JUMP [out]			function contractHoldEth() pub...
    tag 11			function getUserBalance(addres...
      JUMPDEST 			function getUserBalance(addres...
      PUSH 0			uint
      DUP1 			userBalances
      PUSH 0			userBalances[user]
      DUP4 			user
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[user]
      AND 			userBalances[user]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[user]
      AND 			userBalances[user]
      DUP2 			userBalances[user]
      MSTORE 			userBalances[user]
      PUSH 20			userBalances[user]
      ADD 			userBalances[user]
      SWAP1 			userBalances[user]
      DUP2 			userBalances[user]
      MSTORE 			userBalances[user]
      PUSH 20			userBalances[user]
      ADD 			userBalances[user]
      PUSH 0			userBalances[user]
      KECCAK256 			userBalances[user]
      SLOAD 			userBalances[user]
      SWAP1 			return userBalances[user]
      POP 			return userBalances[user]
      SWAP2 			function getUserBalance(addres...
      SWAP1 			function getUserBalance(addres...
      POP 			function getUserBalance(addres...
      JUMP [out]			function getUserBalance(addres...
    tag 14			function withdrawBalance() pub...
      JUMPDEST 			function withdrawBalance() pub...
      PUSH 0			uint amountToWithdraw
      DUP1 			userBalances
      PUSH 0			userBalances[msg.sender]
      CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      SWAP1 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      PUSH 0			userBalances[msg.sender]
      KECCAK256 			userBalances[msg.sender]
      SLOAD 			userBalances[msg.sender]
      SWAP1 			uint amountToWithdraw = userBa...
      POP 			uint amountToWithdraw = userBa...
      PUSH 3042FBBF8FB97FB253117BDF7C2385C241B9EAF856A585675CE0521E592CA7A5			Name(msg.sender)
      CALLER 			msg.sender
      PUSH 40			Name(msg.sender)
      MLOAD 			Name(msg.sender)
      DUP1 			Name(msg.sender)
      DUP3 			Name(msg.sender)
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			Name(msg.sender)
      AND 			Name(msg.sender)
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			Name(msg.sender)
      AND 			Name(msg.sender)
      DUP2 			Name(msg.sender)
      MSTORE 			Name(msg.sender)
      PUSH 20			Name(msg.sender)
      ADD 			Name(msg.sender)
      SWAP2 			Name(msg.sender)
      POP 			Name(msg.sender)
      POP 			Name(msg.sender)
      PUSH 40			Name(msg.sender)
      MLOAD 			Name(msg.sender)
      DUP1 			Name(msg.sender)
      SWAP2 			Name(msg.sender)
      SUB 			Name(msg.sender)
      SWAP1 			Name(msg.sender)
      LOG1 			Name(msg.sender)
      PUSH 0			false
      ISZERO 			msg.sender.call.value(amountTo...
      ISZERO 			msg.sender.call.value(amountTo...
      CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			msg.sender.call
      AND 			msg.sender.call
      DUP3 			amountToWithdraw
      PUSH 40			msg.sender.call.value(amountTo...
      MLOAD 			msg.sender.call.value(amountTo...
      PUSH 0			msg.sender.call.value(amountTo...
      PUSH 40			msg.sender.call.value(amountTo...
      MLOAD 			msg.sender.call.value(amountTo...
      DUP1 			msg.sender.call.value(amountTo...
      DUP4 			msg.sender.call.value(amountTo...
      SUB 			msg.sender.call.value(amountTo...
      DUP2 			msg.sender.call.value(amountTo...
      DUP6 			msg.sender.call.value(amountTo...
      DUP8 			msg.sender.call.value(amountTo...
      GAS 			msg.sender.call.value(amountTo...
      CALL 			msg.sender.call.value(amountTo...
      SWAP3 			msg.sender.call.value(amountTo...
      POP 			msg.sender.call.value(amountTo...
      POP 			msg.sender.call.value(amountTo...
      POP 			msg.sender.call.value(amountTo...
      ISZERO 			msg.sender.call.value(amountTo...
      ISZERO 			msg.sender.call.value(amountTo...
      EQ 			msg.sender.call.value(amountTo...
      ISZERO 			if (msg.sender.call.value(amou...
      PUSH [tag] 20			if (msg.sender.call.value(amou...
      JUMPI 			if (msg.sender.call.value(amou...
      PUSH 0			revert()
      DUP1 			revert()
      REVERT 			revert()
    tag 20			if (msg.sender.call.value(amou...
      JUMPDEST 			if (msg.sender.call.value(amou...
      PUSH 0			0
      DUP1 			userBalances
      PUSH 0			userBalances[msg.sender]
      CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      SWAP1 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      PUSH 0			userBalances[msg.sender]
      KECCAK256 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender] = 0
      SWAP1 			userBalances[msg.sender] = 0
      SSTORE 			userBalances[msg.sender] = 0
      POP 			userBalances[msg.sender] = 0
      POP 			function withdrawBalance() pub...
      JUMP [out]			function withdrawBalance() pub...
    tag 16			function addToBalance() public...
      JUMPDEST 			function addToBalance() public...
      CALLVALUE 			msg.value
      PUSH 0			userBalances
      DUP1 			userBalances[msg.sender]
      CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      SWAP1 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      PUSH 0			userBalances[msg.sender]
      KECCAK256 			userBalances[msg.sender]
      SLOAD 			userBalances[msg.sender]
      ADD 			userBalances[msg.sender] + msg...
      PUSH 0			userBalances
      DUP1 			userBalances[msg.sender]
      CALLER 			msg.sender
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      PUSH FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF			userBalances[msg.sender]
      AND 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      SWAP1 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender]
      MSTORE 			userBalances[msg.sender]
      PUSH 20			userBalances[msg.sender]
      ADD 			userBalances[msg.sender]
      PUSH 0			userBalances[msg.sender]
      KECCAK256 			userBalances[msg.sender]
      DUP2 			userBalances[msg.sender] = use...
      SWAP1 			userBalances[msg.sender] = use...
      SSTORE 			userBalances[msg.sender] = use...
      POP 			userBalances[msg.sender] = use...
      JUMP [out]			function addToBalance() public...
    .data
